; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:portenta_c33]
platform = renesas-ra
board = portenta_c33
framework = arduino

lib_extra_dirs =
    third_party

lib_deps =
    file://third_party/SE05X/SE05X

build_flags =
    -Iinclude
    -Ipsa/include
    -Ithird_party/SE05X/SE05X/src

