#ifndef CA_CERT_H
#define CA_CERT_H

const char ca_cert_pem[] = 
"-----BEGIN CERTIFICATE-----\n"
"MIIDfzCCAmegAwIBAgIUPxbFzcKWfgnG3GG+HXACqGt+GBgwDQYJKoZIhvcNAQEL\n"
"BQAwTzELMAkGA1UEBhMCSVQxDDAKBgNVBAgMA0ZWRzEOMAwGA1UEBwwFVWRpbmUx\n"
"EDAOBgNVBAoMB1Rlc3RPcmcxEDAOBgNVBAMMB01RVFQgQ0EwHhcNMjYwMzA0MjEw\n"
"OTQxWhcNMzYwMzAxMjEwOTQxWjBPMQswCQYDVQQGEwJJVDEMMAoGA1UECAwDRlZH\n"
"MQ4wDAYDVQQHDAVVZGluZTEQMA4GA1UECgwHVGVzdE9yZzEQMA4GA1UEAwwHTVFU\n"
"VCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMmJ9YdzCD1F9bCe\n"
"9ueaVvBv25wt1N0kxd1uU+LDUSxZ2RX0/za9r6TVlKqOySxNUrXlOa7q0f7QqwF6\n"
"l2efJ3rglgsn4E3yFZXTGTn5G5Z9CBnI79+V0OGW2xIFIfPTC05epzvGgb1GWLU9\n"
"yRDNJRs49XrkX8yLYVlErDkWgFHACGAiGRzm64/sx4o8dn6d4OKjQkG0Fnq8b0TY\n"
"BLOYaXgIf8PgaU4jdqQMURS3ADsFzMEEzuGtuBEsAsAuEoJXv3wGwpqtdJVX4YEf\n"
"Nu8IEAbmnyMkZjLFlTqq42Xo/WwgYdugLuzXev2Ef1jeGKR3yhRAkmsWZRpWgjLc\n"
"FI5ZC2UCAwEAAaNTMFEwHQYDVR0OBBYEFD3amY9GFjg5kNgbePZArDDGAdV+MB8G\n"
"A1UdIwQYMBaAFD3amY9GFjg5kNgbePZArDDGAdV+MA8GA1UdEwEB/wQFMAMBAf8w\n"
"DQYJKoZIhvcNAQELBQADggEBAJdLZ0UKZ9sWtCBnCGUPdUdXhnUZjTAwavXfLZMk\n"
"GKnmS+DRgTtqnopfPsJxAe34E0SZpu8IKMRKyaYwhM/THnEYnxeASW3WNxEtbfVr\n"
"7qJ4VE524jUyyD3LY2mI2hMgK+ceQXbIvYxUs7QklE77OvIHzWxpb3Oksqc8H55o\n"
"O+XZavUOvw3Z6Olnx/+zPsefy2rKRlHKNyaIIM6KYbj3oeZo5vUY0dBXXKX4ko7G\n"
"m1F4u/VVpclILqKl69bnzAecytMzyAgJ0DuwaS3PVKPLOgy/257wIcopHKB/1X2l\n"
"XKmbG4HRWEmRl4X4ZF48/0vHBzAM9VTe1h5TimKL8/J3pdQ=\n"
"-----END CERTIFICATE-----\n"
;

const size_t ca_cert_pem_len = sizeof(ca_cert_pem);

#endif
