#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

/* Platform */
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_NO_PLATFORM_ENTROPY

/* RNG / Entropy */
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_PSA_CRYPTO_CLIENT

/* PSA Crypto */
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_USE_PSA_CRYPTO
#define MBEDTLS_PK_C
#define MBEDTLS_PK_HAVE_ECC_KEYS   
#define MBEDTLS_PK_RSA_ALT_SUPPORT  

/* Hashes */
#define MBEDTLS_MD_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_OID_C

/* PK / ECC / ECDSA */
#define MBEDTLS_PK_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED

/* AES / GCM */
#define MBEDTLS_AES_C
#define MBEDTLS_GCM_C

/* TLS */
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_MAX_CONTENT_LEN 4096

/* X.509 */
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C

/* Optional Debug */
#ifdef CONFIG_MBEDTLS_DEBUG
#define MBEDTLS_DEBUG_C
#define MBEDTLS_ERROR_C
#endif

#endif /* MBEDTLS_CONFIG_H */